language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_script:
  - mkdir -p ./__code_coverage__
script:
  - ./.travis-script.sh
after_success:
  - yarn run semantic-release
  - ./.travis-after-script.sh
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
